# Generated by Django 2.0 on 2020-03-05 11:59

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productimage',
            field=models.ImageField(upload_to=products.models.upload_productimage),
        ),
    ]
