# Generated by Django 2.0 on 2020-03-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200305_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subcategoryname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory'),
        ),
    ]
