# Generated by Django 2.2 on 2020-07-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='createat',
            new_name='createdat',
        ),
    ]
